"""update task list table

Revision ID: 6bd9e081de08
Revises: 1a71b07be70f
Create Date: 2025-11-09 13:18:16.437836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bd9e081de08'
down_revision: Union[str, Sequence[str], None] = '1a71b07be70f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_lists', sa.Column('color', sa.String(length=7), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_lists', 'color')
    # ### end Alembic commands ###
